image: ghcr.io/robotology/robots-configuration:latest
github:
  prebuilds:
    master: false
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
tasks:
- name: Install
  command: |
    mkdir -p build && cd build
    cmake .. \
          -DCMAKE_PREFIX_PATH=${DEPENDENCIES_DIR}/install \
          -DCMAKE_INSTALL_PREFIX=${DEPENDENCIES_DIR}/install \
          -DBUILD_TESTING:BOOL=ON \
          -DINSTALL_ALL_ROBOTS:BOOL=ON
    cmake --build . --config Release --target install